In [327]:
import pandas as pd
import numpy as np

In [328]:
df = pd.read_csv('online.csv')

In [329]:
df.isnull().sum()

Marketing Spend    3
Administration     0
Transport          7
Area               0
Profit             0
dtype: int64

In [330]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Marketing Spend  47 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        43 non-null     float64
 3   Area             50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [331]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

In [332]:

num_columns = ['Marketing Spend', 'Transport']
df[num_columns] = imputer.fit_transform(df[num_columns])

In [333]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [334]:
df.dtypes

Marketing Spend    float64
Administration     float64
Transport          float64
Area                object
Profit             float64
dtype: object

In [335]:
pd.get_dummies(df)

,Marketing Spend,Administration,Transport,Profit,Area_Ctg,Area_Dhaka,Area_Rangpur
0,114523.610000,136897.80,471784.100000,192261.83,False,True,False
1,162597.700000,151377.59,443898.530000,191792.06,True,False,False
2,153441.510000,101145.55,407934.540000,191050.39,False,False,True
3,144372.410000,118671.85,383199.620000,182901.99,False,True,False
4,142107.340000,91391.77,213456.050698,166187.94,False,False,True
5,73056.624681,99814.71,362861.360000,156991.12,False,True,False
6,134615.460000,147198.87,127716.820000,156122.51,True,False,False
7,130298.130000,145530.06,323876.680000,155752.60,False,False,True
8,73056.624681,116353.80,311613.290000,152211.77,False,True,False
9,123334.880000,108679.17,304981.620000,149759.96,True,False,False
10,101913.080000,110594.11,229160.950000,146121.95,False,False,True
11,100671.960000,91790.61,213456.050698,144259.40,True,False,False
12,93863.750000,127320.38,249839.440000,141585.52,False,False,True
13,91992.390000,135495.07,252664.930000,134307.35,True,False,False
14,119943.240000,156547.42,256512.920000,132602.65,False,False,True
15,165349.200000,122616.84,261776.230000,129917.04,False,True,False
16,78013.110000,121597.55,264346.060000,126992.93,True,False,False
17,94657.160000,145077.58,282574.310000,125370.37,False,True,False
18,91749.160000,114175.79,294919.570000,124266.90,False,False,True
19,86419.700000,153514.11,0.000000,122776.86,False,True,False
20,76253.860000,113867.30,298664.470000,118474.03,True,False,False
21,78389.470000,153773.43,299737.290000,111313.02,False,True,False
22,73994.560000,122782.75,303319.260000,110352.25,False,False,True
23,67532.530000,105751.03,304768.730000,108733.99,False,False,True
24,77044.010000,99281.34,213456.050698,108552.04,False,True,False
25,64664.710000,139553.16,137962.620000,107404.34,True,False,False
26,75328.870000,144135.98,134050.070000,105733.54,False,False,True
27,72107.600000,127864.55,353183.810000,105008.31,False,True,False
28,66051.520000,182645.56,118148.200000,103282.38,False,False,True
29,65605.480000,153032.06,107138.380000,101004.64,False,True,False
30,61994.480000,115641.28,91131.240000,99937.59,False,False,True
31,61136.380000,152701.92,88218.230000,97483.56,False,True,False
32,63408.860000,129219.61,46085.250000,97427.84,True,False,False
33,55493.950000,103057.49,214634.810000,96778.92,False,False,True
34,46426.070000,157693.92,213456.050698,96712.80,True,False,False
35,46014.020000,85047.44,205517.640000,96479.51,False,True,False
36,28663.760000,127056.21,201126.820000,90708.19,False,False,True
37,44069.950000,51283.14,213456.050698,89949.14,True,False,False
38,20229.590000,65947.93,185265.100000,81229.06,False,True,False
39,38558.510000,82982.09,174999.300000,81005.76,True,False,False
40,28754.330000,118546.05,213456.050698,78239.91,True,False,False
41,27892.920000,84710.77,164470.710000,77798.83,False,False,True
42,23640.930000,96189.63,148001.110000,71498.49,True,False,False
43,15505.730000,127382.30,213456.050698,69758.98,False,True,False
44,22177.740000,154806.14,28334.720000,65200.33,True,False,False
45,1000.230000,124153.04,1903.930000,64926.08,False,True,False
46,1315.460000,115816.21,297114.460000,49490.75,False,False,True
47,73056.624681,135426.92,0.000000,42559.73,True,False,False
48,542.050000,51743.15,0.000000,35673.41,False,True,False
49,0.000000,116983.80,45173.060000,14681.40,True,False,False

In [336]:
from sklearn.preprocessing import OneHotEncoder

en = OneHotEncoder(sparse=False)

df['Area'] = en.fit_transform(df[['Area']])

SyntaxError: invalid syntax (243110609.py, line 5)

In [ ]:
df

    Marketing Spend  Administration      Transport  Area     Profit
0     114523.610000       136897.80  471784.100000   0.0  192261.83
1     162597.700000       151377.59  443898.530000   1.0  191792.06
2     153441.510000       101145.55  407934.540000   0.0  191050.39
3     144372.410000       118671.85  383199.620000   0.0  182901.99
4     142107.340000        91391.77  213456.050698   0.0  166187.94
5      73056.624681        99814.71  362861.360000   0.0  156991.12
6     134615.460000       147198.87  127716.820000   1.0  156122.51
7     130298.130000       145530.06  323876.680000   0.0  155752.60
8      73056.624681       116353.80  311613.290000   0.0  152211.77
9     123334.880000       108679.17  304981.620000   1.0  149759.96
10    101913.080000       110594.11  229160.950000   0.0  146121.95
11    100671.960000        91790.61  213456.050698   1.0  144259.40
12     93863.750000       127320.38  249839.440000   0.0  141585.52
13     91992.390000       135495.07  252664.930000   1.0  134307.35
14    119943.240000       156547.42  256512.920000   0.0  132602.65
15    165349.200000       122616.84  261776.230000   0.0  129917.04
16     78013.110000       121597.55  264346.060000   1.0  126992.93
17     94657.160000       145077.58  282574.310000   0.0  125370.37
18     91749.160000       114175.79  294919.570000   0.0  124266.90
19     86419.700000       153514.11       0.000000   0.0  122776.86
20     76253.860000       113867.30  298664.470000   1.0  118474.03
21     78389.470000       153773.43  299737.290000   0.0  111313.02
22     73994.560000       122782.75  303319.260000   0.0  110352.25
23     67532.530000       105751.03  304768.730000   0.0  108733.99
24     77044.010000        99281.34  213456.050698   0.0  108552.04
25     64664.710000       139553.16  137962.620000   1.0  107404.34
26     75328.870000       144135.98  134050.070000   0.0  105733.54
27     72107.600000       127864.55  353183.810000   0.0  105008.31
28     66051.520000       182645.56  118148.200000   0.0  103282.38
29     65605.480000       153032.06  107138.380000   0.0  101004.64
30     61994.480000       115641.28   91131.240000   0.0   99937.59
31     61136.380000       152701.92   88218.230000   0.0   97483.56
32     63408.860000       129219.61   46085.250000   1.0   97427.84
33     55493.950000       103057.49  214634.810000   0.0   96778.92
34     46426.070000       157693.92  213456.050698   1.0   96712.80
35     46014.020000        85047.44  205517.640000   0.0   96479.51
36     28663.760000       127056.21  201126.820000   0.0   90708.19
37     44069.950000        51283.14  213456.050698   1.0   89949.14
38     20229.590000        65947.93  185265.100000   0.0   81229.06
39     38558.510000        82982.09  174999.300000   1.0   81005.76
40     28754.330000       118546.05  213456.050698   1.0   78239.91
41     27892.920000        84710.77  164470.710000   0.0   77798.83
42     23640.930000        96189.63  148001.110000   1.0   71498.49
43     15505.730000       127382.30  213456.050698   0.0   69758.98
44     22177.740000       154806.14   28334.720000   1.0   65200.33
45      1000.230000       124153.04    1903.930000   0.0   64926.08
46      1315.460000       115816.21  297114.460000   0.0   49490.75
47     73056.624681       135426.92       0.000000   1.0   42559.73
48       542.050000        51743.15       0.000000   0.0   35673.41
49         0.000000       116983.80   45173.060000   1.0   14681.40

In [ ]:
df.keys()

Index(['Marketing Spend', 'Administration', 'Transport', 'Area', 'Profit'], dtype='object')